config/routes.rb
Rails.application.routes.draw do
  get 'sales/index'
  get 'orders/index'
  get 'work_items/new'
  get 'work_items/index'
  get 'work_progresses/new'
  get 'work_progresses/index'
  get 'work_progress/new'
  get 'work_progress/index'
  get 'work_processes/new'
  get 'work_processes/index'
  resources :machines
  resources :employees
  resources :work_statuses

  root to: 't_order#index'
  
  get 't_order/index'
  get 't_order/index_a'
  get 't_order/index_b'
  

  get 'order_trns/index'
  get 'order_trns/index_image'
  
  get 'order_trns/show'
  patch 'order_trns/:id/edit', to: 'order_trns#edit' 

  get 'order_headers/index'
  get 'order_headers/show'

  #get 'top/index'
  #root to: 'top#index'

  resources :tokuis
  resources :gaityus
  resources :tantos
#  devise_for :users
#  get 'home/index'
#  get 'home/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root to: "ulists#index"


  

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  get 'users/index' 
  resources :users
  resources :ulists
  resources :support_histories

  #get 'orderheaders/index'
  resources :order_headers
  resources :order_trns
  
  get 'search', to: 'ulists#search'



  resources :employees
  resources :machines
  resources :work_statuses

  get 'wprocesses/index2', to: 'wprocesses#index2', as: 'wprocesses_index2'
  get 'wprocesses/index3', to: 'wprocesses#index3', as: 'wprocesses_index3'
  get 'wprocesses/index', to: 'wprocesses#index', as: 'wprocesses_index'
  get 'wprocesses' => 'wprocesses#index2'

  resources :wprocesses, except: :index do
    get 'index2', on: :collection
    resources :work_items
    collection do
      patch 'update_data', to: 'wprocesses#update_data'
    end
  end
  
  resources :wprocesses do
    member do
      patch :complete
    end
  end

  resources :wprocesses do
    resources :work_items
  end
  
  resources :work_items do
    member do
      patch :start
      patch :complete
    end
  end

#  delete 'delete_selected_work_items', to: 'work_items#delete_selected_work_items', as: 'delete_selected_work_items'

  resources :work_items do
    collection do
      delete :delete_selected
    end
  end

  get 'orders', to: 'orders#index', as: 'orders'
  
  resources :orders do
    collection do
      get 'sort_by_noki'
    end
    member do
      get 'detail', to: 'orders#detail', as: 'order_detail' # 受注詳細のルート
    end
  end
  
  get 'sales', to: 'sales#index', as: 'sales'

  resources :invoices do
    collection do
      post :create_from_kokyaku
    end
  end

  # POSTリクエスト用のルート
  post 'delete_selected_invoices', to: 'invoices#delete_selected', as: 'delete_selected_invoices'

  # DELETEリクエスト用のルート
  delete 'delete_selected_invoices', to: 'invoices#delete_selected'

  post 'send_selected_invoices', to: 'invoices#send_selected'

  resources :c_orders do
    collection do
      post :import
    end
  end
end

app/models/gaityu.rb
class Gaityu < ApplicationRecord
    has_many :wprocesses, foreign_key: 'gaityucd', primary_key: 'gai_cd'

    has_many :t_orders1, foreign_key: 'gaityucd1', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders2, foreign_key: 'gaityucd2', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders1, foreign_key: 'gaityucd3', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders2, foreign_key: 'gaityucd4', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders1, foreign_key: 'gaityucd5', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders2, foreign_key: 'gaityucd6', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders1, foreign_key: 'gaityucd7', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders2, foreign_key: 'gaityucd8', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders2, foreign_key: 'gaityucd9', primary_key: 'gai_cd', class_name: 'TOrder'
    has_many :t_orders1, foreign_key: 'gaityucd10', primary_key: 'gai_cd', class_name: 'TOrder'
    
end

app/controllers/gaityus_controller.rb
class GaityusController < ApplicationController
  before_action :set_gaityu, only: %i[ show edit update destroy ]

  # GET /gaityus or /gaityus.json
  def index
    @gaityus = Gaityu.all
  end

  # GET /gaityus/1 or /gaityus/1.json
  def show
  end

  # GET /gaityus/new
  def new
    @gaityu = Gaityu.new
  end

  # GET /gaityus/1/edit
  def edit
  end

  # POST /gaityus or /gaityus.json
  def create
    @gaityu = Gaityu.new(gaityu_params)

    respond_to do |format|
      if @gaityu.save
        format.html { redirect_to @gaityu, notice: "Gaityu was successfully created." }
        format.json { render :show, status: :created, location: @gaityu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gaityu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gaityus/1 or /gaityus/1.json
  def update
    respond_to do |format|
      if @gaityu.update(gaityu_params)
        format.html { redirect_to @gaityu, notice: "Gaityu was successfully updated." }
        format.json { render :show, status: :ok, location: @gaityu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gaityu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gaityus/1 or /gaityus/1.json
  def destroy
    @gaityu.destroy
    respond_to do |format|
      format.html { redirect_to gaityus_url, notice: "Gaityu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gaityu
      @gaityu = Gaityu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gaityu_params
      params.require(:gaityu).permit(:gai_cd, :gai_name, :gai_kana, :gai_ryaku, :gai_naiyo, :yuko_kbn)
    end
end

app/helpers/gaityus_helper.rb
module GaityusHelper
end

app/views/gaityus/_form.html.erb
<%= form_with(model: gaityu, local: true) do |form| %>
  <% if gaityu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gaityu.errors.count, "error") %> prohibited this gaityu from being saved:</h2>

      <ul>
      <% gaityu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gai_cd %>
    <%= form.text_field :gai_cd %>
  </div>

  <div class="field">
    <%= form.label :gai_name %>
    <%= form.text_field :gai_name %>
  </div>

  <div class="field">
    <%= form.label :gai_kana %>
    <%= form.text_field :gai_kana %>
  </div>

  <div class="field">
    <%= form.label :gai_ryaku %>
    <%= form.text_field :gai_ryaku %>
  </div>

  <div class="field">
    <%= form.label :gai_naiyo %>
    <%= form.text_field :gai_naiyo %>
  </div>

  <div class="field">
    <%= form.label :yuko_kbn %>
    <%= form.number_field :yuko_kbn %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gaityus/edit.html.erb
<h1>Editing Gaityu</h1>

<%= render 'form', gaityu: @gaityu %>

<%= link_to 'Show', @gaityu %> |
<%= link_to 'Back', gaityus_path %>

app/views/gaityus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gaityus</h1>

<table>
  <thead>
    <tr>
      <th>Gai cd</th>
      <th>Gai name</th>
      <th>Gai kana</th>
      <th>Gai ryaku</th>
      <th>Gai naiyo</th>
      <th>Yuko kbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gaityus.each do |gaityu| %>
      <tr>
        <td><%= gaityu.gai_cd %></td>
        <td><%= gaityu.gai_name %></td>
        <td><%= gaityu.gai_kana %></td>
        <td><%= gaityu.gai_ryaku %></td>
        <td><%= gaityu.gai_naiyo %></td>
        <td><%= gaityu.yuko_kbn %></td>
        <td><%= link_to 'Show', gaityu %></td>
        <td><%= link_to 'Edit', edit_gaityu_path(gaityu) %></td>
        <td><%= link_to 'Destroy', gaityu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gaityu', new_gaityu_path %>

app/views/gaityus/new.html.erb
<h1>New Gaityu</h1>

<%= render 'form', gaityu: @gaityu %>

<%= link_to 'Back', gaityus_path %>

app/views/gaityus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gai cd:</strong>
  <%= @gaityu.gai_cd %>
</p>

<p>
  <strong>Gai name:</strong>
  <%= @gaityu.gai_name %>
</p>

<p>
  <strong>Gai kana:</strong>
  <%= @gaityu.gai_kana %>
</p>

<p>
  <strong>Gai ryaku:</strong>
  <%= @gaityu.gai_ryaku %>
</p>

<p>
  <strong>Gai naiyo:</strong>
  <%= @gaityu.gai_naiyo %>
</p>

<p>
  <strong>Yuko kbn:</strong>
  <%= @gaityu.yuko_kbn %>
</p>

<%= link_to 'Edit', edit_gaityu_path(@gaityu) %> |
<%= link_to 'Back', gaityus_path %>