config/routes.rb
Rails.application.routes.draw do
  get 'sales/index'
  get 'orders/index'
  get 'work_items/new'
  get 'work_items/index'
  get 'work_progresses/new'
  get 'work_progresses/index'
  get 'work_progress/new'
  get 'work_progress/index'
  get 'work_processes/new'
  get 'work_processes/index'
  resources :machines
  resources :employees
  resources :work_statuses

  root to: 't_order#index'
  
  get 't_order/index'
  get 't_order/index_a'
  get 't_order/index_b'
  

  get 'order_trns/index'
  get 'order_trns/index_image'
  
  get 'order_trns/show'
  patch 'order_trns/:id/edit', to: 'order_trns#edit' 

  get 'order_headers/index'
  get 'order_headers/show'

  #get 'top/index'
  #root to: 'top#index'

  resources :tokuis
  resources :gaityus
  resources :tantos
#  devise_for :users
#  get 'home/index'
#  get 'home/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root to: "ulists#index"


  

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  get 'users/index' 
  resources :users
  resources :ulists
  resources :support_histories

  #get 'orderheaders/index'
  resources :order_headers
  resources :order_trns
  
  get 'search', to: 'ulists#search'



  resources :employees
  resources :machines
  resources :work_statuses

  get 'wprocesses/index2', to: 'wprocesses#index2', as: 'wprocesses_index2'
  get 'wprocesses/index3', to: 'wprocesses#index3', as: 'wprocesses_index3'
  get 'wprocesses/index', to: 'wprocesses#index', as: 'wprocesses_index'
  get 'wprocesses' => 'wprocesses#index2'

  resources :wprocesses, except: :index do
    get 'index2', on: :collection
    resources :work_items
    collection do
      patch 'update_data', to: 'wprocesses#update_data'
    end
  end
  
  resources :wprocesses do
    member do
      patch :complete
    end
  end

  resources :wprocesses do
    resources :work_items
  end
  
  resources :work_items do
    member do
      patch :start
      patch :complete
    end
  end

#  delete 'delete_selected_work_items', to: 'work_items#delete_selected_work_items', as: 'delete_selected_work_items'

  resources :work_items do
    collection do
      delete :delete_selected
    end
  end

  get 'orders', to: 'orders#index', as: 'orders'
  
  resources :orders do
    collection do
      get 'sort_by_noki'
    end
    member do
      get 'detail', to: 'orders#detail', as: 'order_detail' # 受注詳細のルート
    end
  end
  
  get 'sales', to: 'sales#index', as: 'sales'

  resources :invoices do
    collection do
      post :create_from_kokyaku
    end
  end

  # POSTリクエスト用のルート
  post 'delete_selected_invoices', to: 'invoices#delete_selected', as: 'delete_selected_invoices'

  # DELETEリクエスト用のルート
  delete 'delete_selected_invoices', to: 'invoices#delete_selected'

  post 'send_selected_invoices', to: 'invoices#send_selected'

  resources :c_orders do
    collection do
      post :import
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :work_items
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:employee_name, :skill)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>Employee name:</strong>
    <%= employee.employee_name %>
  </p>

  <p>
    <strong>Skill:</strong>
    <%= employee.skill %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :employee_name, style: "display: block" %>
    <%= form.text_field :employee_name %>
  </div>

  <div>
    <%= form.label :skill, style: "display: block" %>
    <%= form.text_field :skill %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employees</h1>

<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Show this employee", employee %>
    </p>
  <% end %>
</div>

<%= link_to "New employee", new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>