config/routes.rb
Rails.application.routes.draw do
  get 'sales/index'
  get 'orders/index'
  get 'work_items/new'
  get 'work_items/index'
  get 'work_progresses/new'
  get 'work_progresses/index'
  get 'work_progress/new'
  get 'work_progress/index'
  get 'work_processes/new'
  get 'work_processes/index'
  resources :machines
  resources :employees
  resources :work_statuses

  root to: 't_order#index'
  
  get 't_order/index'
  get 't_order/index_a'
  get 't_order/index_b'
  

  get 'order_trns/index'
  get 'order_trns/index_image'
  
  get 'order_trns/show'
  patch 'order_trns/:id/edit', to: 'order_trns#edit' 

  get 'order_headers/index'
  get 'order_headers/show'

  #get 'top/index'
  #root to: 'top#index'

  resources :tokuis
  resources :gaityus
  resources :tantos
#  devise_for :users
#  get 'home/index'
#  get 'home/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root to: "ulists#index"


  

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  get 'users/index' 
  resources :users
  resources :ulists
  resources :support_histories

  #get 'orderheaders/index'
  resources :order_headers
  resources :order_trns
  
  get 'search', to: 'ulists#search'



  resources :employees
  resources :machines
  resources :work_statuses

  get 'wprocesses/index2', to: 'wprocesses#index2', as: 'wprocesses_index2'
  get 'wprocesses/index3', to: 'wprocesses#index3', as: 'wprocesses_index3'
  get 'wprocesses/index', to: 'wprocesses#index', as: 'wprocesses_index'
  get 'wprocesses' => 'wprocesses#index2'

  resources :wprocesses, except: :index do
    get 'index2', on: :collection
    resources :work_items
    collection do
      patch 'update_data', to: 'wprocesses#update_data'
    end
  end
  
  resources :wprocesses do
    member do
      patch :complete
    end
  end

  resources :wprocesses do
    resources :work_items
  end
  
  resources :work_items do
    member do
      patch :start
      patch :complete
    end
  end

#  delete 'delete_selected_work_items', to: 'work_items#delete_selected_work_items', as: 'delete_selected_work_items'

  resources :work_items do
    collection do
      delete :delete_selected
    end
  end

  get 'orders', to: 'orders#index', as: 'orders'
  
  resources :orders do
    collection do
      get 'sort_by_noki'
    end
    member do
      get 'detail', to: 'orders#detail', as: 'order_detail' # 受注詳細のルート
    end
  end
  
  get 'sales', to: 'sales#index', as: 'sales'

  resources :invoices do
    collection do
      post :create_from_kokyaku
    end
  end

  # POSTリクエスト用のルート
  post 'delete_selected_invoices', to: 'invoices#delete_selected', as: 'delete_selected_invoices'

  # DELETEリクエスト用のルート
  delete 'delete_selected_invoices', to: 'invoices#delete_selected'

  post 'send_selected_invoices', to: 'invoices#send_selected'

  resources :c_orders do
    collection do
      post :import
    end
  end
end

app/models/tanto.rb
class Tanto < ApplicationRecord
    has_many :t_orders, foreign_key: 'tanto_cd', primary_key: 'tanto_id'
end

app/controllers/tantos_controller.rb
class TantosController < ApplicationController
  before_action :set_tanto, only: %i[ show edit update destroy ]

  # GET /tantos or /tantos.json
  def index
    @tantos = Tanto.all
  end

  # GET /tantos/1 or /tantos/1.json
  def show
  end

  # GET /tantos/new
  def new
    @tanto = Tanto.new
  end

  # GET /tantos/1/edit
  def edit
  end

  # POST /tantos or /tantos.json
  def create
    @tanto = Tanto.new(tanto_params)

    respond_to do |format|
      if @tanto.save
        format.html { redirect_to @tanto, notice: "Tanto was successfully created." }
        format.json { render :show, status: :created, location: @tanto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tanto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tantos/1 or /tantos/1.json
  def update
    respond_to do |format|
      if @tanto.update(tanto_params)
        format.html { redirect_to @tanto, notice: "Tanto was successfully updated." }
        format.json { render :show, status: :ok, location: @tanto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tanto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tantos/1 or /tantos/1.json
  def destroy
    @tanto.destroy
    respond_to do |format|
      format.html { redirect_to tantos_url, notice: "Tanto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tanto
      @tanto = Tanto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tanto_params
      params.require(:tanto).permit(:tanto_cd, :tanto_name)
    end
end

app/helpers/tantos_helper.rb
module TantosHelper
end

app/views/tantos/_form.html.erb
<%= form_with(model: tanto, local: true) do |form| %>
  <% if tanto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tanto.errors.count, "error") %> prohibited this tanto from being saved:</h2>

      <ul>
      <% tanto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tanto_cd %>
    <%= form.text_field :tanto_cd %>
  </div>

  <div class="field">
    <%= form.label :tanto_name %>
    <%= form.text_field :tanto_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tantos/edit.html.erb
<h1>Editing Tanto</h1>

<%= render 'form', tanto: @tanto %>

<%= link_to 'Show', @tanto %> |
<%= link_to 'Back', tantos_path %>

app/views/tantos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tantos</h1>

<table>
  <thead>
    <tr>
      <th>Tanto cd</th>
      <th>Tanto name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tantos.each do |tanto| %>
      <tr>
        <td><%= tanto.tanto_cd %></td>
        <td><%= tanto.tanto_name %></td>
        <td><%= link_to 'Show', tanto %></td>
        <td><%= link_to 'Edit', edit_tanto_path(tanto) %></td>
        <td><%= link_to 'Destroy', tanto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tanto', new_tanto_path %>

app/views/tantos/new.html.erb
<h1>New Tanto</h1>

<%= render 'form', tanto: @tanto %>

<%= link_to 'Back', tantos_path %>

app/views/tantos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tanto cd:</strong>
  <%= @tanto.tanto_cd %>
</p>

<p>
  <strong>Tanto name:</strong>
  <%= @tanto.tanto_name %>
</p>

<%= link_to 'Edit', edit_tanto_path(@tanto) %> |
<%= link_to 'Back', tantos_path %>