config/routes.rb
Rails.application.routes.draw do
  get 'sales/index'
  get 'orders/index'
  get 'work_items/new'
  get 'work_items/index'
  get 'work_progresses/new'
  get 'work_progresses/index'
  get 'work_progress/new'
  get 'work_progress/index'
  get 'work_processes/new'
  get 'work_processes/index'
  resources :machines
  resources :employees
  resources :work_statuses

  root to: 't_order#index'
  
  get 't_order/index'
  get 't_order/index_a'
  get 't_order/index_b'
  

  get 'order_trns/index'
  get 'order_trns/index_image'
  
  get 'order_trns/show'
  patch 'order_trns/:id/edit', to: 'order_trns#edit' 

  get 'order_headers/index'
  get 'order_headers/show'

  #get 'top/index'
  #root to: 'top#index'

  resources :tokuis
  resources :gaityus
  resources :tantos
#  devise_for :users
#  get 'home/index'
#  get 'home/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root to: "ulists#index"


  

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  get 'users/index' 
  resources :users
  resources :ulists
  resources :support_histories

  #get 'orderheaders/index'
  resources :order_headers
  resources :order_trns
  
  get 'search', to: 'ulists#search'



  resources :employees
  resources :machines
  resources :work_statuses

  get 'wprocesses/index2', to: 'wprocesses#index2', as: 'wprocesses_index2'
  get 'wprocesses/index3', to: 'wprocesses#index3', as: 'wprocesses_index3'
  get 'wprocesses/index', to: 'wprocesses#index', as: 'wprocesses_index'
  get 'wprocesses' => 'wprocesses#index2'

  resources :wprocesses, except: :index do
    get 'index2', on: :collection
    resources :work_items
    collection do
      patch 'update_data', to: 'wprocesses#update_data'
    end
  end
  
  resources :wprocesses do
    member do
      patch :complete
    end
  end

  resources :wprocesses do
    resources :work_items
  end
  
  resources :work_items do
    member do
      patch :start
      patch :complete
    end
  end

#  delete 'delete_selected_work_items', to: 'work_items#delete_selected_work_items', as: 'delete_selected_work_items'

  resources :work_items do
    collection do
      delete :delete_selected
    end
  end

  get 'orders', to: 'orders#index', as: 'orders'
  
  resources :orders do
    collection do
      get 'sort_by_noki'
    end
    member do
      get 'detail', to: 'orders#detail', as: 'order_detail' # 受注詳細のルート
    end
  end
  
  get 'sales', to: 'sales#index', as: 'sales'

  resources :invoices do
    collection do
      post :create_from_kokyaku
    end
  end

  # POSTリクエスト用のルート
  post 'delete_selected_invoices', to: 'invoices#delete_selected', as: 'delete_selected_invoices'

  # DELETEリクエスト用のルート
  delete 'delete_selected_invoices', to: 'invoices#delete_selected'

  post 'send_selected_invoices', to: 'invoices#send_selected'

  resources :c_orders do
    collection do
      post :import
    end
  end
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: %i[ show edit update destroy ]

  # GET /machines or /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1 or /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines or /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to machine_url(@machine), notice: "Machine was successfully created." }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1 or /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to machine_url(@machine), notice: "Machine was successfully updated." }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1 or /machines/1.json
  def destroy
    @machine.destroy!

    respond_to do |format|
      format.html { redirect_to machines_url, notice: "Machine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def machine_params
      params.require(:machine).permit(:machine_name, :naiyo, :place)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_with(model: machine) do |form| %>
  <% if machine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
        <% machine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :machine_name, style: "display: block" %>
    <%= form.text_field :machine_name %>
  </div>

  <div>
    <%= form.label :naiyo, style: "display: block" %>
    <%= form.text_field :naiyo %>
  </div>

  <div>
    <%= form.label :place, style: "display: block" %>
    <%= form.text_field :place %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/_machine.html.erb
<div id="<%= dom_id machine %>">
  <p>
    <strong>Machine name:</strong>
    <%= machine.machine_name %>
  </p>

  <p>
    <strong>Naiyo:</strong>
    <%= machine.naiyo %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= machine.place %>
  </p>

</div>

app/views/machines/edit.html.erb
<h1>Editing machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Show this machine", @machine %> |
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Machines</h1>

<div id="machines">
  <% @machines.each do |machine| %>
    <%= render machine %>
    <p>
      <%= link_to "Show this machine", machine %>
    </p>
  <% end %>
</div>

<%= link_to "New machine", new_machine_path %>

app/views/machines/new.html.erb
<h1>New machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @machine %>

<div>
  <%= link_to "Edit this machine", edit_machine_path(@machine) %> |
  <%= link_to "Back to machines", machines_path %>

  <%= button_to "Destroy this machine", @machine, method: :delete %>
</div>